### ISSUE TITLE
stockalert down?

### ISSUE THREAD

**Issue by thob** [Nexination/node-telegram-bot-collection#1]
seems I can't add stocks, tried AMZN

**Comment by KrisZane** [comment]
I just added AMZN without any problems. Can you run me through how you do it?

**Comment by thob** [comment]
⊥homas β, [29.01.16 10:47]
/stockadd AMZN

⊥homas β, [29.01.16 10:47]
/settings

Stock Alert, [29.01.16 10:47]
Your settings: 
none

**Comment by KrisZane** [comment]
You have to use it like so:
/stockadd
amzn

Due to the nature of how telegram behaves and works with auto completion, I am using a prompt scheme, you issue the command and it asks you to input your stock. :)
